version: '2.2'
services:
  web:
    build: .
    ports:
      - "34846:5000"
    cpus: 0.5
    mem_limit: 128m
    restart: on-failure
  redis:
    image: "redis:alpine"
    cpus: 0.1
    mem_limit: 128m
    restart: on-failure
